### ISSUE TITLE
Add shadows for falling barrels

### ISSUE THREAD

**Issue by mlodato517** [deepgram-devs/GarbageGame#4]

**Comment by nikolawhallon** [comment]
first attempt here: https://github.com/deepgram-devs/GarbageGame/pull/6

**Comment by mlodato517** [comment]
Not sure which one you'll look at first so I'll duplicate here but, something cool is that if you say something like ["fixes #4"](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests#linking-a-pull-request-to-an-issue) in your PR description GitHub will automatically link the issue and PR and then automatically close the issue when the PR is merged.

**Comment by nikolawhallon** [comment]
I don't understand but I can try it.

**Comment by mlodato517** [comment]
Closed by #6
